spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gateway?allowPublicKeyRetrieval=true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hieunm123.ptit@gmail.com
    password: ynpgqidwyqsuynqv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:db/master.xml
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081
application:
  token:
    key: ShopSport123@tjukjgkgfyhvjyjrtcrftxgrxjuyhzygtxgresxcx
    expire-time-access-token: 300000
    expire-time-refresh-token: 8640000
