spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hieu
    password: 1234
    url: jdbc:mysql://localhost:33061/database?allowPublicKeyRetrieval=true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hieunm123.ptit@gmail.com
    password: ynpgqidwyqsuynqv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:db/master.xml
  data:
    redis:
      host: localhost
      port: 6378
server:
  port: 8083
application:
  token:
    key: ShopSport123@tjukjgkgfyhvjyjrtcrftxgrxjuyhzygtxgresxcx
    expire-time-access-token: 300000
    expire-time-refresh-token: 8640000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
